
function [ E, U, subP] = ...
    computeApproxEnergy(labeling, DCapprox, energy, optOptions,myString)
    U = computeUnaryEnergyForLabeling(DCapprox.approxUE, labeling);
    subP = computeSubPairwiseEnergyForLabeling(energy.subPE, labeling);
    E = U + subP; % 
    
    if optOptions.SHOW_FLAG
        fprintf('Seg: APPROXIMATE ENERGY OF %s LABELING (E = U + subP): %f = %f + %f \n', ...
            myString,...
            double(E),...
            double(U),...
            double(subP));
    end
end