function [ E, U, superP, subP] = computeEnergy(labeling, energy,  optOptions, myString)
%energy structure:
% E.UE, E.subPE, E.superPE, E.constTerm,

U = computeUnaryEnergyForLabeling(energy.UE,labeling);
subP = computeSubPairwiseEnergyForLabeling(energy.subPE, labeling);
superP = computeSuperPairwiseEnergyForLabeling(energy.superPE, labeling);
E = U + superP + subP + energy.constTerm;
if optOptions.SHOW_FLAG
    fprintf('Seg: ACTUAL ENERGY OF %s LABELING (E = U + superP + subP + const.): %f = %f + %f + %f + %f\n', ...
        myString,...
        double(E),...
        double(U),...
        double(superP),...
        double(subP),...
        double(energy.constTerm));
%     fprintf('Seg: ACTUAL ENERGY OF %s LABELING (E = Etemp + const.): %f = %f + %f\n', ...
%         myString,...
%         double(E),...
%         double(U + superP + subP),...
%         double(energy.constTerm));
end

end
